#!/bin/bash

###通用脚本,Linux MacOS通用
#!/bin/bash

#Add myscript path to PATH
export PATH="${PATH}:/usr/local/scripts"

#export ALL_PROXY=socks5://127.0.0.1:1086

alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias grep='grep --color=auto'

#Colorful for Terminal
# 不加判断,加快执行速度

alias ls='gls --color=auto'
alias dir='gdir --color=auto'
alias grep='gdir --color=auto'

alias grep='grep --color'
alias egrep='egrep --color'
alias fgrep='fgrep --color'

eval $(gdircolors ~/opensource/dircolors-solarized/dircolors.ansi-dark)

alias ping="ping -c 5"
alias tree="tree -N"

#alias for cnpm
alias cnpm="npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc"

export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook'

screenfetch

#MacOS专用脚本
#Setting for Java
export JAVA_7_HOME=`/usr/libexec/java_home -v 1.7`
export JAVA_8_HOME=`/usr/libexec/java_home -v 1.8`
export JAVA_9_HOME=`/usr/libexec/java_home -v 9`
export JAVA_10_HOME=`/usr/libexec/java_home -v 10`
export JAVA_11_HOME=`/usr/libexec/java_home -v 11`

export JAVA_HOME=$JAVA_11_HOME
alias jdk7="export JAVA_HOME=${JAVA_7_HOME}"
alias jdk8="export JAVA_HOME=${JAVA_8_HOME}"
alias jdk9="export JAVA_HOME=${JAVA_9_HOME}"
alias jdk10="export JAVA_HOME=${JAVA_10_HOME}"
alias jdk11="export JAVA_HOME=${JAVA_11_HOME}"

export GRAALVM_HOME=/usr/local/graalvm-ce/Contents/Home
export PATH=$GRAALVM_HOME/bin:$PATH

export QT_HOME="/Users/chenlong/Qt5.9.1/5.9.1/clang_64"
export PATH="${QT_HOME}/bin:${PATH}"

export PATH=$PATH:/usr/local/sbin
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh
export BXSHARE=/usr/local/Cellar/bochs/2.6.9_2/share/bochs
