#!/bin/zsh

alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias grep='grep --color=auto'

#Colorful for Terminal
# 不加判断,加快执行速度

alias ls='gls --color=auto'
alias dir='gdir --color=auto'
alias grep='gdir --color=auto'

alias grep='grep --color'
alias egrep='egrep --color'
alias fgrep='fgrep --color'

eval $(gdircolors ~/local/opensource/dircolors-solarized/dircolors.ansi-dark)

alias ping="ping -c 5"
alias tree="tree -N"




temp(){
  cd `mktemp -d`
 }


eval "$(brew shellenv zsh)"

# fnm
eval "$(fnm env --shell zsh)"

proxy() {
  export http_proxy=http://127.0.0.1:7890
  export https_proxy=http://127.0.0.1:7890
  export all_proxy=http://127.0.0.1:7890
  git config --global http.proxy http://127.0.0.1:7890
  git config --global https.proxy http://127.0.0.1:7890
  echo "Proxy enabled: http://127.0.0.1:7890"
}

unproxy() {
  unset http_proxy https_proxy all_proxy
  git config --global --unset http.proxy
  git config --global --unset https.proxy
  echo "Proxy disabled"
}


export PNPM_HOME="/Users/chenlong/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# 定义重写逻辑的函数
rewrite-claude-to-glm() {
    # 使用 Zsh 的参数扩展功能进行全局替换
    # $BUFFER 代表当前命令行输入的内容
    BUFFER="${BUFFER//claude-sonnet-4-6/glm-5}"

    # 执行原生的 accept-line 操作（即确认执行命令）
    zle .accept-line
}

# 将该函数注册为一个 ZLE 小部件 (Widget)
zle -N accept-line rewrite-claude-to-glm

#Setting for Java
export JAVA_8_HOME=$(/usr/libexec/java_home -v 1.8)
export JAVA_17_HOME=$(/usr/libexec/java_home -v 17)
export JAVA_25_HOME=$(/usr/libexec/java_home -v 25)
export JAVA_26_HOME=$(/usr/libexec/java_home -v 26)

export JAVA_HOME=$JAVA_25_HOME
alias jdk8="export JAVA_HOME=${JAVA_8_HOME}"
alias jdk17="export JAVA_HOME=${JAVA_17_HOME}"
alias jdk25="export JAVA_HOME=${JAVA_25_HOME}"
alias jdk26="export JAVA_HOME=${JAVA_26_HOME}"

