#!/bin/zsh

#Add myscript path to PATH
export PATH="${PATH}:/usr/local/scripts"

alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias grep='grep --color=auto'

#Colorful for Terminal
# 不加判断,加快执行速度

alias ls='gls --color=auto'
alias dir='gdir --color=auto'
alias grep='gdir --color=auto'

alias grep='grep --color'
alias egrep='egrep --color'
alias fgrep='fgrep --color'

eval $(gdircolors ~/local/opensource/dircolors-solarized/dircolors.ansi-dark)

alias ping="ping -c 5"
alias tree="tree -N"


export PATH=$PATH:/usr/local/sbin
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh
export BXSHARE=/usr/local/Cellar/bochs/2.6.9_2/share/bochs


temp(){
  cd `mktemp -d`
 }

pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish


eval "$(brew shellenv zsh)"

# fnm
eval "$(fnm env --shell zsh)"

proxy() {
  export http_proxy=http://127.0.0.1:7890
  export https_proxy=http://127.0.0.1:7890
  export all_proxy=http://127.0.0.1:7890
  git config --global http.proxy http://127.0.0.1:7890
  git config --global https.proxy http://127.0.0.1:7890
  echo "Proxy enabled: http://127.0.0.1:7890"
}

unproxy() {
  unset http_proxy https_proxy all_proxy
  git config --global --unset http.proxy
  git config --global --unset https.proxy
  echo "Proxy disabled"
}


export PNPM_HOME="/Users/chenlong/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

source ~/.customerc.local

