# Text/source files → Visual Studio Code
com.microsoft.VSCode	net.daringfireball.markdown	editor
com.microsoft.VSCode	public.css	editor
com.microsoft.VSCode	public.json	editor
com.microsoft.VSCode	public.script	editor
com.microsoft.VSCode	public.source-code	editor
com.microsoft.VSCode	public.rtf	editor
com.microsoft.VSCode	public.plain-text	editor
com.microsoft.VSCode	public.unix-executable	editor
com.microsoft.VSCode	public.c-header	editor
com.microsoft.VSCode	public.c-plus-plus-source	editor
com.microsoft.VSCode	public.c-source	editor
com.microsoft.VSCode	public.objective-c-source	editor
com.microsoft.VSCode	public.perl-script	editor
com.microsoft.VSCode	public.python-script	editor
com.microsoft.VSCode	public.ruby-script	editor
com.microsoft.VSCode	public.shell-script	editor
com.microsoft.VSCode	public.xml	editor
com.microsoft.VSCode	public.yaml	editor
com.microsoft.VSCode	org.oasis-open.xliff	editor
com.microsoft.VSCode	com.netscape.javascript-source	editor
com.microsoft.VSCode	org.tex.latex	editor
com.microsoft.VSCode	org.tug.tex	editor
com.microsoft.VSCode	net.daringfireball.markdown	editor
com.microsoft.VSCode	io.unsigned.dubbo	editor
com.microsoft.VSCode	io.unsigned.properties	editor
com.microsoft.VSCode	com.apple.xcode.toml	editor
com.microsoft.VSCode	org.json.json5	editor
com.microsoft.VSCode	org.opencontainers.compose.editor	editor

# Image/PDF → system defaults (keep macOS defaults)
# com.apple.Preview	public.png	viewer
# com.apple.Preview	public.jpeg	viewer
# com.apple.Preview	com.adobe.pdf	viewer
